import { readdir, writeFile } from "node:fs/promises";
import { join, parse } from "node:path";

const CATS_DIR = join(process.cwd(), "public/img/api/v1");
const OUTPUT_FILE = join(process.cwd(), "src/cats.ts");

console.log("🐱 Generatiing cat list...");

try {
  const files = await readdir(CATS_DIR);
  
  // Filter for .svg files and remove extension via parse().name
  const cats = files
    .filter((file) => file.endsWith(".svg"))
    .map((file) => parse(file).name)
    .sort(); // Sort alphabetically for consistency

  const content = `// This file is auto-generated by scripts/generate-cats.ts
// Do not edit manually.

const cats = ${JSON.stringify(cats, null, 4)} as const;

export default cats;
`;

  await writeFile(OUTPUT_FILE, content);
  console.log(`✅ Successfully generated src/cats.ts with ${cats.length} cats!`);
} catch (error) {
  console.error("❌ Error generating cat list:", error);
  process.exit(1);
}
