// This file is auto-generated by scripts/generate-cats.ts
// Do not edit manually.

const cats = [
    "announcer",
    "art",
    "award",
    "book",
    "bug",
    "cat",
    "comic",
    "gaming",
    "general",
    "groups",
    "idea",
    "news",
    "support",
    "tv"
] as const;

export default cats;
